import os

POSTGRES_SERVER = os.getenv("POSTGRES_SERVER", "localhost")
POSTGRES_USER = os.getenv("POSTGRES_USER", "postgres")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD")
POSTGRES_DB = os.getenv("POSTGRES_DB", "postgres")

SQLALCHEMY_DATABASE_URI = f"postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}@db:5432/{POSTGRES_DB}"


# Test db
TEST_POSTGRES_SERVER = os.getenv("TEST_POSTGRES_SERVER", "localhost")
TEST_POSTGRES_USER = os.getenv("TEST_POSTGRES_USER", "postgres")
TEST_POSTGRES_PASSWORD = os.getenv("TEST_POSTGRES_PASSWORD")
TEST_POSTGRES_DB = os.getenv("TEST_POSTGRES_DB", "postgres")
TEST_PGPORT = os.getenv("TEST_PGPORT", 5432)
TEST_SQLALCHEMY_DATABASE_URI = (
    f"postgresql://{TEST_POSTGRES_USER}:{TEST_POSTGRES_PASSWORD}@test_db:{TEST_PGPORT}/{TEST_POSTGRES_DB}"
)
