"""empty message

Revision ID: abdbbe173b41
Revises: c0e8704ecc7d
Create Date: 2022-03-28 18:19:26.538252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abdbbe173b41'
down_revision = 'c0e8704ecc7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('temperature_dt_key', 'temperature', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('temperature_dt_key', 'temperature', ['dt'])
    # ### end Alembic commands ###
